"""add total_balance to user

Revision ID: 021b6e732483
Revises: 1e7398ff8e2f
Create Date: 2025-11-18 14:27:43.863839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021b6e732483'
down_revision = '1e7398ff8e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_balance')

    # ### end Alembic commands ###
