"""add deduct_from to transaction

Revision ID: 07af53334287
Revises: 5d0c9d70c6ad
Create Date: 2025-11-20 21:23:23.153763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07af53334287'
down_revision = '5d0c9d70c6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduct_from', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('deduct_from')

    # ### end Alembic commands ###
