"""add user preferences fields

Revision ID: 119119c1fccd
Revises: 9b3e7d0439c1
Create Date: 2025-11-17 21:22:34.156648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119119c1fccd'
down_revision = '9b3e7d0439c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_push', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('currency')
        batch_op.drop_column('notify_push')
        batch_op.drop_column('notify_email')

    # ### end Alembic commands ###
