"""add budget_id to transactions

Revision ID: 1e7398ff8e2f
Revises: 119119c1fccd
Create Date: 2025-11-18 14:09:51.317653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7398ff8e2f'
down_revision = '119119c1fccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_budget_id', 'budget', ['budget_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_budget_id', type_='foreignkey')
        batch_op.drop_column('budget_id')

    # ### end Alembic commands ###
