"""add funding_source to budget

Revision ID: 5d0c9d70c6ad
Revises: 021b6e732483
Create Date: 2025-11-20 20:29:00.500997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0c9d70c6ad'
down_revision = '021b6e732483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('funding_source')

    # ### end Alembic commands ###
