"""add loan date range and monthly due date to debt

Revision ID: 816369c88cc9
Revises: 97886179c3c6
Create Date: 2025-11-20 22:17:00.175423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816369c88cc9'
down_revision = '97886179c3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('loan_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('monthly_due_date', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('monthly_due_date')
        batch_op.drop_column('loan_end_date')
        batch_op.drop_column('loan_start_date')

    # ### end Alembic commands ###
